version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=invoices_db
      - POSTGRES_USER=jano
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
